# Build js and css
FROM node:lts-alpine as node_build
WORKDIR /www
COPY package.json ./
RUN npm install
COPY resources/ ./resources/
COPY public/ ./public/
COPY dev/build/ ./dev/build/
RUN npm run production

FROM php:8.1-fpm-buster as final
RUN set -x; \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev  \
        libldap2-dev  \
        libtidy-dev  \
        libxml2-dev  \
        fontconfig  \
        fonts-freefont-ttf   \
        wget \
        tar \
        curl \
        libzip-dev \
        unzip \
	&& wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb \
	&& chmod a+x ./wkhtmltox_0.12.6-1.buster_amd64.deb \
    && apt-get install -y ./wkhtmltox_0.12.6-1.buster_amd64.deb \
    && rm ./wkhtmltox_0.12.6-1.buster_amd64.deb \
    && docker-php-ext-install -j$(nproc) dom pdo pdo_mysql zip tidy  \
    && docker-php-ext-configure ldap \
    && docker-php-ext-install -j$(nproc) ldap \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
RUN apt-get remove -y git && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY dev/ee/fpm/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY --chmod=775 dev/ee/fpm/docker-entrypoint.sh /bin/docker-entrypoint.sh
COPY . /var/www/bookstack/
COPY --from=node_build /www/public/dist /var/www/bookstack/public/dist/

ARG COMPOSER_VERSION=2.1.12
RUN set -x; \
    cd /var/www/bookstack \
    && curl -sS https://getcomposer.org/installer | php -- --version=$COMPOSER_VERSION \
    && /var/www/bookstack/composer.phar install -v -d /var/www/bookstack/ \
    && rm -rf /var/www/bookstack/composer.phar /root/.composer

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

RUN chown -R www:www /var/www/bookstack

WORKDIR /var/www/bookstack

# www-data
USER www

VOLUME ["/var/www/bookstack/public", "/var/www/bookstack/storage/uploads"]

EXPOSE 9000

CMD ["/bin/docker-entrypoint.sh"]